export const SEQUELIZE = 'SEQUELIZE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const EXAMSTUDENT_REPOSITORY = 'EXAMSTUDENT_REPOSITORY';
export const EXAM_REPOSITORY = 'EXAM_REPOSITORY';
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';